[package]
name = "rust-native-dapp-realworld-example-app"
version = "0.1.0"
authors = ["Hunter Trujillo <hunter@cryptoquick.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
