name: Rust Nightly Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: rustup toolchain install nightly && rustup default nightly
      - name: Build
        run: cargo build --verbose
      - name: Linters
        run: cargo fmt -- --check
      - name: Run tests
        run: cargo test --verbose
